# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
version=0.1.0
group=com.ianwijma.poweroffarts
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-2
mod_name=Power Of Farts
mod_author=Ian Wijma
mod_id=poweroffarts
license=All Rights Reserved
description=The power of farts, now in Minecraft.

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.160.0+26.2
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.87

# Integrations
# JEI, see https://maven.blamejared.com/mezz/jei/jei-26.2-common-api/ for new versions
jei_version=30.32.0.215
# Jade, see https://modrinth.com/mod/jade/versions for new versions
jade_version_neoforge=26.2.10+neoforge
jade_version_fabric=26.2.11+fabric
# TeamReborn Energy (Fabric), see https://maven.fabricmc.net/teamreborn/energy/ for new versions
team_reborn_energy_version=5.0.0
