license = "${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="${mod_id}.png"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jade"
type = "optional"
versionRange = "[26.2.10,)"
ordering = "AFTER"
side = "BOTH"
